# Generated by Django 5.2.3 on 2025-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('superadmin', 'Супер Админ'), ('executor', 'Частный Судоисполнитель'), ('assistant', 'Помощник ЧСИ')], max_length=20, unique=True),
        ),
    ]
