# Generated by Django 5.2.3 on 2025-07-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, choices=[('Almaty', 'Алматы'), ('Astana', 'Астана'), ('Shymkent', 'Шымкент'), ('Akmola', 'Акмолинская'), ('Aktobe', 'Актюбинская'), ('AlmatyRegion', 'Алматинская'), ('Atyrau', 'Атырауская'), ('EastKazakhstan', 'Восточно-Казахстанская'), ('Zhambyl', 'Жамбылская'), ('WestKazakhstan', 'Западно-Казахстанская'), ('Karaganda', 'Карагандинская'), ('Kostanay', 'Костанайская'), ('Kyzylorda', 'Кызылординская'), ('Mangystau', 'Мангистауская'), ('Pavlodar', 'Павлодарская'), ('NorthKazakhstan', 'Северо-Казахстанская'), ('Turkestan', 'Туркестанская'), ('Ulytau', 'Улытауская')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('superadmin', 'Супер Админ'), ('executor', 'Частный Судоисполнитель'), ('assistant', 'Помощник ЧСИ'), ('accountant', 'Бухгалтер')], max_length=20, unique=True),
        ),
    ]
