# Generated by Django 5.2.3 on 2025-07-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceeding_id', models.CharField(max_length=100)),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('judge', models.CharField(blank=True, max_length=255, null=True)),
                ('case_number', models.CharField(max_length=100)),
                ('case_status', models.CharField(max_length=100)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('debtor', models.CharField(max_length=255)),
                ('claimant', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('period_of_request', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
